/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_interfaces;

import javax.swing.ImageIcon;

/**
 *
 * @author danie
 */
public class PrincipalInterface extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalInterface
     */
    private PrincipalInterface(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Icon_App.png")).getImage());
    }
    
    /**
     * Creates new form PrincipalInterface
     * @param userType
     */
    public PrincipalInterface(String userType) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Icon_App.png")).getImage());
        
        switch(userType){
            case "Master":
                
                break;
            
            case "None":
                
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        Panel_MenuBar = new javax.swing.JPanel();
        Label_ExitButton = new javax.swing.JLabel();
        Panel_MasterOptions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Panel_Dashboard = new javax.swing.JPanel();
        Panel_Users = new javax.swing.JPanel();
        Panel_Clients = new javax.swing.JPanel();
        Panel_Suppliers = new javax.swing.JPanel();
        Panel_Products = new javax.swing.JPanel();
        Panel_Sells = new javax.swing.JPanel();
        Panel_Buys = new javax.swing.JPanel();
        Panel_Production = new javax.swing.JPanel();
        Panel_Inventory = new javax.swing.JPanel();
        Panel_Reports = new javax.swing.JPanel();

        jLabel11.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Productos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_MenuBar.setBackground(new java.awt.Color(255, 97, 50));

        Label_ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteExitDoor_32px.png"))); // NOI18N
        Label_ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ExitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_MenuBarLayout = new javax.swing.GroupLayout(Panel_MenuBar);
        Panel_MenuBar.setLayout(Panel_MenuBarLayout);
        Panel_MenuBarLayout.setHorizontalGroup(
            Panel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MenuBarLayout.createSequentialGroup()
                .addContainerGap(796, Short.MAX_VALUE)
                .addComponent(Label_ExitButton)
                .addContainerGap())
        );
        Panel_MenuBarLayout.setVerticalGroup(
            Panel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 840, 40));

        Panel_MasterOptions.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(80, 80, 80));
        jLabel1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de gestion empresarial");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Pagina Principal");

        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 97, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_OrangeDashboard_32px.png"))); // NOI18N
        jLabel3.setText("   Tablero");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"))); // NOI18N
        jLabel4.setText("   Proveedores");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"))); // NOI18N
        jLabel5.setText("   Clientes");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteTag_32px.png"))); // NOI18N
        jLabel6.setText("   Productos");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Operaciones");

        jLabel8.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteSell_32px.png"))); // NOI18N
        jLabel8.setText("     Ventas");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteSell_32px.png"))); // NOI18N
        jLabel9.setText("     Compras");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteInventory_32px.png"))); // NOI18N
        jLabel10.setText("   Inventario");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteReport_32px.png"))); // NOI18N
        jLabel12.setText("    Reportes");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"))); // NOI18N
        jLabel13.setText("   Usuarios");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteProduction_32px.png"))); // NOI18N
        jLabel14.setText("   Produccion");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout Panel_MasterOptionsLayout = new javax.swing.GroupLayout(Panel_MasterOptions);
        Panel_MasterOptions.setLayout(Panel_MasterOptionsLayout);
        Panel_MasterOptionsLayout.setHorizontalGroup(
            Panel_MasterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addGroup(Panel_MasterOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_MasterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_MasterOptionsLayout.createSequentialGroup()
                        .addGroup(Panel_MasterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Panel_MasterOptionsLayout.setVerticalGroup(
            Panel_MasterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MasterOptionsLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_MasterOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 650));

        Panel_Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Dashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_DashboardLayout = new javax.swing.GroupLayout(Panel_Dashboard);
        Panel_Dashboard.setLayout(Panel_DashboardLayout);
        Panel_DashboardLayout.setHorizontalGroup(
            Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_DashboardLayout.setVerticalGroup(
            Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Users.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Users.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_UsersLayout = new javax.swing.GroupLayout(Panel_Users);
        Panel_Users.setLayout(Panel_UsersLayout);
        Panel_UsersLayout.setHorizontalGroup(
            Panel_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_UsersLayout.setVerticalGroup(
            Panel_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Clients.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Clients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_ClientsLayout = new javax.swing.GroupLayout(Panel_Clients);
        Panel_Clients.setLayout(Panel_ClientsLayout);
        Panel_ClientsLayout.setHorizontalGroup(
            Panel_ClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_ClientsLayout.setVerticalGroup(
            Panel_ClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Suppliers.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Suppliers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_SuppliersLayout = new javax.swing.GroupLayout(Panel_Suppliers);
        Panel_Suppliers.setLayout(Panel_SuppliersLayout);
        Panel_SuppliersLayout.setHorizontalGroup(
            Panel_SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_SuppliersLayout.setVerticalGroup(
            Panel_SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Products.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Products.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_ProductsLayout = new javax.swing.GroupLayout(Panel_Products);
        Panel_Products.setLayout(Panel_ProductsLayout);
        Panel_ProductsLayout.setHorizontalGroup(
            Panel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_ProductsLayout.setVerticalGroup(
            Panel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Products, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Sells.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Sells.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_SellsLayout = new javax.swing.GroupLayout(Panel_Sells);
        Panel_Sells.setLayout(Panel_SellsLayout);
        Panel_SellsLayout.setHorizontalGroup(
            Panel_SellsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_SellsLayout.setVerticalGroup(
            Panel_SellsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Sells, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Buys.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Buys.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_BuysLayout = new javax.swing.GroupLayout(Panel_Buys);
        Panel_Buys.setLayout(Panel_BuysLayout);
        Panel_BuysLayout.setHorizontalGroup(
            Panel_BuysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_BuysLayout.setVerticalGroup(
            Panel_BuysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Buys, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Production.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Production.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_ProductionLayout = new javax.swing.GroupLayout(Panel_Production);
        Panel_Production.setLayout(Panel_ProductionLayout);
        Panel_ProductionLayout.setHorizontalGroup(
            Panel_ProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_ProductionLayout.setVerticalGroup(
            Panel_ProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Inventory.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Inventory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_InventoryLayout = new javax.swing.GroupLayout(Panel_Inventory);
        Panel_Inventory.setLayout(Panel_InventoryLayout);
        Panel_InventoryLayout.setHorizontalGroup(
            Panel_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_InventoryLayout.setVerticalGroup(
            Panel_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Reports.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_ReportsLayout = new javax.swing.GroupLayout(Panel_Reports);
        Panel_Reports.setLayout(Panel_ReportsLayout);
        Panel_ReportsLayout.setHorizontalGroup(
            Panel_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_ReportsLayout.setVerticalGroup(
            Panel_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Label_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ExitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Label_ExitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_ExitButton;
    private javax.swing.JPanel Panel_Buys;
    private javax.swing.JPanel Panel_Clients;
    private javax.swing.JPanel Panel_Dashboard;
    private javax.swing.JPanel Panel_Inventory;
    private javax.swing.JPanel Panel_MasterOptions;
    private javax.swing.JPanel Panel_MenuBar;
    private javax.swing.JPanel Panel_Production;
    private javax.swing.JPanel Panel_Products;
    private javax.swing.JPanel Panel_Reports;
    private javax.swing.JPanel Panel_Sells;
    private javax.swing.JPanel Panel_Suppliers;
    private javax.swing.JPanel Panel_Users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
