/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_interfaces;

import classes.data_structures.*;
import java.awt.Color;
import javax.swing.ImageIcon;
import classes.others.*;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import org.json.simple.*;
import org.json.simple.parser.*;

/**
 *
 * @author danie
 */
public class PrincipalInterface extends javax.swing.JFrame {
    private AVLTree<User> usersTree;
    private User logedUser;
    private int pressedButton;
    private int mouseX, mouseY;
    
    /**
     * Creates new form PrincipalInterface
     */
    public PrincipalInterface() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Icon_App.png")).getImage());
        this.getContentPane().setBackground(new Color(255,255,255));
    }
    
    /**
     * Creates new form PrincipalInterface
     * @param userType
     */
    public PrincipalInterface(User user) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Icon_App.png")).getImage());
        this.getContentPane().setBackground(new Color(255,255,255));
        
        this.logedUser = user;
        Label_WelcomeMessage.setText("Bienvenido al sistema, " + logedUser.getNickname());
        PanelsOff();
        pressedButton = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        Panel_MenuBar = new javax.swing.JPanel();
        Label_ExitButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Panel_OptionsButtons = new javax.swing.JPanel();
        Label_MenuTitle = new javax.swing.JLabel();
        Label_HomeTitle = new javax.swing.JLabel();
        Label_DashboardButton = new javax.swing.JLabel();
        Label_UsersButton = new javax.swing.JLabel();
        Label_ClientsButton = new javax.swing.JLabel();
        Label_SuppliersButton = new javax.swing.JLabel();
        Label_ProductsButton = new javax.swing.JLabel();
        Label_OperacionesMenu = new javax.swing.JLabel();
        Label_SellsButton = new javax.swing.JLabel();
        Label_BuysButton = new javax.swing.JLabel();
        Label_ProductionButton = new javax.swing.JLabel();
        Label_InventoryButton = new javax.swing.JLabel();
        Label_ReportsButton = new javax.swing.JLabel();
        Panel_Dashboard = new javax.swing.JPanel();
        Label_WelcomeMessage = new javax.swing.JLabel();
        Panel_Users = new javax.swing.JPanel();
        Panel_Clients = new javax.swing.JPanel();
        Panel_Suppliers = new javax.swing.JPanel();
        Panel_Products = new javax.swing.JPanel();
        Panel_Sells = new javax.swing.JPanel();
        Panel_Buys = new javax.swing.JPanel();
        Panel_Production = new javax.swing.JPanel();
        Panel_Inventory = new javax.swing.JPanel();
        Panel_Reports = new javax.swing.JPanel();

        jLabel11.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Productos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_MenuBar.setBackground(new java.awt.Color(255, 97, 50));

        Label_ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteExitDoor_32px.png"))); // NOI18N
        Label_ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ExitButtonMouseClicked(evt);
            }
        });

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel_MenuBarLayout = new javax.swing.GroupLayout(Panel_MenuBar);
        Panel_MenuBar.setLayout(Panel_MenuBarLayout);
        Panel_MenuBarLayout.setHorizontalGroup(
            Panel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MenuBarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ExitButton)
                .addContainerGap())
        );
        Panel_MenuBarLayout.setVerticalGroup(
            Panel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 840, 40));

        Panel_OptionsButtons.setBackground(new java.awt.Color(102, 102, 102));

        Label_MenuTitle.setBackground(new java.awt.Color(80, 80, 80));
        Label_MenuTitle.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        Label_MenuTitle.setForeground(new java.awt.Color(255, 255, 255));
        Label_MenuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_MenuTitle.setText("Sistema de gestion empresarial");
        Label_MenuTitle.setOpaque(true);

        Label_HomeTitle.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        Label_HomeTitle.setForeground(new java.awt.Color(153, 153, 153));
        Label_HomeTitle.setText("Pagina Principal");

        Label_DashboardButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_DashboardButton.setForeground(new java.awt.Color(255, 97, 51));
        Label_DashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_OrangeDashboard_32px.png"))); // NOI18N
        Label_DashboardButton.setText("   Tablero");
        Label_DashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_DashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_DashboardButtonMouseClicked(evt);
            }
        });

        Label_UsersButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_UsersButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_UsersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"))); // NOI18N
        Label_UsersButton.setText("   Usuarios");
        Label_UsersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_UsersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_UsersButtonMouseClicked(evt);
            }
        });

        Label_ClientsButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_ClientsButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_ClientsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"))); // NOI18N
        Label_ClientsButton.setText("   Clientes");
        Label_ClientsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ClientsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ClientsButtonMouseClicked(evt);
            }
        });

        Label_SuppliersButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_SuppliersButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_SuppliersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"))); // NOI18N
        Label_SuppliersButton.setText("   Proveedores");
        Label_SuppliersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_SuppliersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_SuppliersButtonMouseClicked(evt);
            }
        });

        Label_ProductsButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_ProductsButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_ProductsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteTag_32px.png"))); // NOI18N
        Label_ProductsButton.setText("   Productos");
        Label_ProductsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ProductsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ProductsButtonMouseClicked(evt);
            }
        });

        Label_OperacionesMenu.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        Label_OperacionesMenu.setForeground(new java.awt.Color(153, 153, 153));
        Label_OperacionesMenu.setText("Operaciones");

        Label_SellsButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_SellsButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_SellsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteSell_32px.png"))); // NOI18N
        Label_SellsButton.setText("     Ventas");
        Label_SellsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_SellsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_SellsButtonMouseClicked(evt);
            }
        });

        Label_BuysButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_BuysButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_BuysButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteSell_32px.png"))); // NOI18N
        Label_BuysButton.setText("     Compras");
        Label_BuysButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_BuysButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_BuysButtonMouseClicked(evt);
            }
        });

        Label_ProductionButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_ProductionButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_ProductionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteProduction_32px.png"))); // NOI18N
        Label_ProductionButton.setText("   Produccion");
        Label_ProductionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ProductionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ProductionButtonMouseClicked(evt);
            }
        });

        Label_InventoryButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_InventoryButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_InventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteInventory_32px.png"))); // NOI18N
        Label_InventoryButton.setText("   Inventario");
        Label_InventoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_InventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_InventoryButtonMouseClicked(evt);
            }
        });

        Label_ReportsButton.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_ReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        Label_ReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_WhiteReport_32px.png"))); // NOI18N
        Label_ReportsButton.setText("    Reportes");
        Label_ReportsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ReportsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ReportsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_OptionsButtonsLayout = new javax.swing.GroupLayout(Panel_OptionsButtons);
        Panel_OptionsButtons.setLayout(Panel_OptionsButtonsLayout);
        Panel_OptionsButtonsLayout.setHorizontalGroup(
            Panel_OptionsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_MenuTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addGroup(Panel_OptionsButtonsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Panel_OptionsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_DashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_OptionsButtonsLayout.createSequentialGroup()
                        .addGroup(Panel_OptionsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_HomeTitle)
                            .addComponent(Label_OperacionesMenu))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Label_UsersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_ClientsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_SuppliersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_ProductsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_SellsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_BuysButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_ProductionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_InventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_ReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Panel_OptionsButtonsLayout.setVerticalGroup(
            Panel_OptionsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_OptionsButtonsLayout.createSequentialGroup()
                .addComponent(Label_MenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_HomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_DashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_UsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ClientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_SuppliersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_OperacionesMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_SellsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_BuysButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ProductionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_InventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_OptionsButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 650));

        Panel_Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Dashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        Label_WelcomeMessage.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Label_WelcomeMessage.setForeground(new java.awt.Color(255, 97, 51));
        Label_WelcomeMessage.setText("Bienvenido al sistema,");

        javax.swing.GroupLayout Panel_DashboardLayout = new javax.swing.GroupLayout(Panel_Dashboard);
        Panel_Dashboard.setLayout(Panel_DashboardLayout);
        Panel_DashboardLayout.setHorizontalGroup(
            Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_WelcomeMessage)
                .addContainerGap(646, Short.MAX_VALUE))
        );
        Panel_DashboardLayout.setVerticalGroup(
            Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_WelcomeMessage)
                .addContainerGap(570, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Users.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Users.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_UsersLayout = new javax.swing.GroupLayout(Panel_Users);
        Panel_Users.setLayout(Panel_UsersLayout);
        Panel_UsersLayout.setHorizontalGroup(
            Panel_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_UsersLayout.setVerticalGroup(
            Panel_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Clients.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Clients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_ClientsLayout = new javax.swing.GroupLayout(Panel_Clients);
        Panel_Clients.setLayout(Panel_ClientsLayout);
        Panel_ClientsLayout.setHorizontalGroup(
            Panel_ClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_ClientsLayout.setVerticalGroup(
            Panel_ClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Suppliers.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Suppliers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_SuppliersLayout = new javax.swing.GroupLayout(Panel_Suppliers);
        Panel_Suppliers.setLayout(Panel_SuppliersLayout);
        Panel_SuppliersLayout.setHorizontalGroup(
            Panel_SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_SuppliersLayout.setVerticalGroup(
            Panel_SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Products.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Products.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_ProductsLayout = new javax.swing.GroupLayout(Panel_Products);
        Panel_Products.setLayout(Panel_ProductsLayout);
        Panel_ProductsLayout.setHorizontalGroup(
            Panel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_ProductsLayout.setVerticalGroup(
            Panel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Products, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Sells.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Sells.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_SellsLayout = new javax.swing.GroupLayout(Panel_Sells);
        Panel_Sells.setLayout(Panel_SellsLayout);
        Panel_SellsLayout.setHorizontalGroup(
            Panel_SellsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_SellsLayout.setVerticalGroup(
            Panel_SellsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Sells, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Buys.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Buys.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_BuysLayout = new javax.swing.GroupLayout(Panel_Buys);
        Panel_Buys.setLayout(Panel_BuysLayout);
        Panel_BuysLayout.setHorizontalGroup(
            Panel_BuysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_BuysLayout.setVerticalGroup(
            Panel_BuysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Buys, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Production.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Production.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_ProductionLayout = new javax.swing.GroupLayout(Panel_Production);
        Panel_Production.setLayout(Panel_ProductionLayout);
        Panel_ProductionLayout.setHorizontalGroup(
            Panel_ProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_ProductionLayout.setVerticalGroup(
            Panel_ProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Inventory.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Inventory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_InventoryLayout = new javax.swing.GroupLayout(Panel_Inventory);
        Panel_Inventory.setLayout(Panel_InventoryLayout);
        Panel_InventoryLayout.setHorizontalGroup(
            Panel_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_InventoryLayout.setVerticalGroup(
            Panel_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        Panel_Reports.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout Panel_ReportsLayout = new javax.swing.GroupLayout(Panel_Reports);
        Panel_Reports.setLayout(Panel_ReportsLayout);
        Panel_ReportsLayout.setHorizontalGroup(
            Panel_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        Panel_ReportsLayout.setVerticalGroup(
            Panel_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 840, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Label_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ExitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Label_ExitButtonMouseClicked

    private void PanelsOff(){
        Panel_Users.setVisible(false);
        Panel_Clients.setVisible(false);
        Panel_Suppliers.setVisible(false);
        Panel_Products.setVisible(false);
        Panel_Sells.setVisible(false);
        Panel_Buys.setVisible(false);
        Panel_Production.setVisible(false);
        Panel_Inventory.setVisible(false);
        Panel_Reports.setVisible(false);
    }
    
    private void MenuButtonsOff(){
        //Panels Off
        switch(pressedButton){
        case 0:
            //Dashboard
            Panel_Dashboard.setVisible(false);
            ImageIcon dashboardOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteDashboard_32px.png"));
            Label_DashboardButton.setIcon(dashboardOff);
            Label_DashboardButton.setForeground(new Color(255,255,255));
            break;

        case 1:
            //Users
            Panel_Users.setVisible(false);
            ImageIcon UsersOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"));
            Label_UsersButton.setIcon(UsersOff);
            Label_UsersButton.setForeground(new Color(255,255,255));
            break;

        case 2:
            //Clients
            Panel_Clients.setVisible(false);
            ImageIcon ClientsOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"));
            Label_ClientsButton.setIcon(ClientsOff);
            Label_ClientsButton.setForeground(new Color(255,255,255));
            break;

        case 3:
            //Suppliers
            Panel_Suppliers.setVisible(false);
            ImageIcon SuppliersOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteTeam_32px.png"));
            Label_SuppliersButton.setIcon(SuppliersOff);
            Label_SuppliersButton.setForeground(new Color(255,255,255));
            break;

        case 4:
            //Products
            Panel_Products.setVisible(false);
            ImageIcon ProductsOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteTag_32px.png"));
            Label_ProductsButton.setIcon(ProductsOff);
            Label_ProductsButton.setForeground(new Color(255,255,255));
            break;

        case 5:
            //Sells
            Panel_Sells.setVisible(false);
            ImageIcon SellsOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteSell_32px.png"));
            Label_SellsButton.setIcon(SellsOff);
            Label_SellsButton.setForeground(new Color(255,255,255));
            break;

        case 6:
            //Buys
            Panel_Buys.setVisible(false);
            ImageIcon BuysOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteSell_32px.png"));
            Label_BuysButton.setIcon(BuysOff);
            Label_BuysButton.setForeground(new Color(255,255,255));
            break;

        case 7:
            //Production
            Panel_Production.setVisible(false);
            ImageIcon ProductionOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteProduction_32px.png"));
            Label_ProductionButton.setIcon(ProductionOff);
            Label_ProductionButton.setForeground(new Color(255,255,255));
            break;

        case 8:
            //Inventory
            Panel_Inventory.setVisible(false);
            ImageIcon InventoryOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteInventory_32px.png"));
            Label_InventoryButton.setIcon(InventoryOff);
            Label_InventoryButton.setForeground(new Color(255,255,255));
            break;

        case 9:
            //Reports
            Panel_Reports.setVisible(false);
            ImageIcon ReportsOff = new ImageIcon(getClass().getResource("/images/Icon_WhiteReport_32px.png"));
            Label_ReportsButton.setIcon(ReportsOff);
            Label_ReportsButton.setForeground(new Color(255,255,255));
            break;
        }
    }
    
    private void Label_DashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_DashboardButtonMouseClicked
        if (pressedButton != 0){
            MenuButtonsOff();
            pressedButton = 0;
        }

        //Changing the panels
        Panel_Dashboard.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon DashboardActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeDashboard_32px.png"));
        Label_DashboardButton.setIcon(DashboardActive);
        Label_DashboardButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_DashboardButtonMouseClicked

    private void Label_UsersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_UsersButtonMouseClicked
        if (pressedButton != 1){
            MenuButtonsOff();
            pressedButton = 1;
        }

        //Changing the panels
        Panel_Users.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon UsersActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeTeam_32px.png"));
        Label_UsersButton.setIcon(UsersActive);
        Label_UsersButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_UsersButtonMouseClicked

    private void Label_ClientsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ClientsButtonMouseClicked
        if (pressedButton != 2){
            MenuButtonsOff();
            pressedButton = 2;
        }

        //Changing the panels
        Panel_Clients.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon ClientsActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeTeam_32px.png"));
        Label_ClientsButton.setIcon(ClientsActive);
        Label_ClientsButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_ClientsButtonMouseClicked

    private void Label_SuppliersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_SuppliersButtonMouseClicked
        if (pressedButton != 3){
            MenuButtonsOff();
           pressedButton = 3;
        }

        //Changing the panels
        Panel_Suppliers.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon SuppliersdActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeTeam_32px.png"));
        Label_SuppliersButton.setIcon(SuppliersdActive);
        Label_SuppliersButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_SuppliersButtonMouseClicked

    private void Label_ProductsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ProductsButtonMouseClicked
        if (pressedButton != 4){
            MenuButtonsOff();
            pressedButton = 4;
        }

        //Changing the panels
        Panel_Products.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon ProductsActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeTag_32px.png"));
        Label_ProductsButton.setIcon(ProductsActive);
        Label_ProductsButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_ProductsButtonMouseClicked

    private void Label_SellsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_SellsButtonMouseClicked
        if (pressedButton != 5){
            MenuButtonsOff();
            pressedButton = 5;
        }

        //Changing the panels
        Panel_Sells.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon SellsActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeSell_32px.png"));
        Label_SellsButton.setIcon(SellsActive);
        Label_SellsButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_SellsButtonMouseClicked

    private void Label_BuysButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_BuysButtonMouseClicked
        if (pressedButton != 6){
            MenuButtonsOff();
            pressedButton = 6;
        }

        //Changing the panels
        Panel_Buys.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon BuysActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeSell_32px.png"));
        Label_BuysButton.setIcon(BuysActive);
        Label_BuysButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_BuysButtonMouseClicked

    private void Label_ProductionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ProductionButtonMouseClicked
        if (pressedButton != 7){
            MenuButtonsOff();
            pressedButton = 7;
        }

        //Changing the panels
        Panel_Production.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon ProductionActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeProduction_32px.png"));
        Label_ProductionButton.setIcon(ProductionActive);
        Label_ProductionButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_ProductionButtonMouseClicked

    private void Label_InventoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_InventoryButtonMouseClicked
        if (pressedButton != 8){
            MenuButtonsOff();
            pressedButton = 8;
        }

        //Changing the panels
        Panel_Inventory.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon InventoryActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeInventory_32px.png"));
        Label_InventoryButton.setIcon(InventoryActive);
        Label_InventoryButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_InventoryButtonMouseClicked

    private void Label_ReportsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ReportsButtonMouseClicked
        if (pressedButton != 9){
            MenuButtonsOff();
            pressedButton = 9;
        }

        //Changing the panels
        Panel_Reports.setVisible(true);
        
        //Switching the buttons Off
        ImageIcon ReportsActive = new ImageIcon(getClass().getResource("/images/Icon_OrangeReport_32px.png"));
        Label_ReportsButton.setIcon(ReportsActive);
        Label_ReportsButton.setForeground(new Color(255,97,50));
    }//GEN-LAST:event_Label_ReportsButtonMouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-mouseX-240, y-mouseY);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed
 
    public void setUsersTree(AVLTree<User> usersTree){
        this.usersTree = usersTree;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_BuysButton;
    private javax.swing.JLabel Label_ClientsButton;
    private javax.swing.JLabel Label_DashboardButton;
    private javax.swing.JLabel Label_ExitButton;
    private javax.swing.JLabel Label_HomeTitle;
    private javax.swing.JLabel Label_InventoryButton;
    private javax.swing.JLabel Label_MenuTitle;
    private javax.swing.JLabel Label_OperacionesMenu;
    private javax.swing.JLabel Label_ProductionButton;
    private javax.swing.JLabel Label_ProductsButton;
    private javax.swing.JLabel Label_ReportsButton;
    private javax.swing.JLabel Label_SellsButton;
    private javax.swing.JLabel Label_SuppliersButton;
    private javax.swing.JLabel Label_UsersButton;
    private javax.swing.JLabel Label_WelcomeMessage;
    private javax.swing.JPanel Panel_Buys;
    private javax.swing.JPanel Panel_Clients;
    private javax.swing.JPanel Panel_Dashboard;
    private javax.swing.JPanel Panel_Inventory;
    private javax.swing.JPanel Panel_MenuBar;
    private javax.swing.JPanel Panel_OptionsButtons;
    private javax.swing.JPanel Panel_Production;
    private javax.swing.JPanel Panel_Products;
    private javax.swing.JPanel Panel_Reports;
    private javax.swing.JPanel Panel_Sells;
    private javax.swing.JPanel Panel_Suppliers;
    private javax.swing.JPanel Panel_Users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    // End of variables declaration//GEN-END:variables
}
